---
# Authors
# -------
#
# Sami Lanu <sami.lanu@tut.fi>
#
# Copyright
# ---------
#
# Copyright 2018 Tampere University of Technology
- name: Create new eventlog for Ansible
  win_eventlog:
    name: AnsibleLog
    sources:
    - Ansible
    state: present
