---
# Authors
# -------
#
# Sami Lanu <sami.lanu@tut.fi>
#
# Copyright
# ---------
#
# Copyright 2018 Tampere University of Technology

cminfra_dsc_fw_tcp80:
  cminfra_include: true
  name: 'cminfra_allowTCP80_AnsibleManaged'
  remoteaddress: Any
  protocol: tcp
  localport: 80
  action: Allow
  direction: inbound
  profile: Any
  enabled: True
  ensure: Present

# Local 'administrators' group
admins:
  group: administrators
  members:
    - member: 'cm-rfa\Administrator'
    - member: 'DOMAIN\CmInfraAdmins'
    - member: 'DOMAIN\ServerOperators'
    - member: 'DOMAIN\cm-ss$'

nosms:
  drives:
    - drive: 'c:\'

features:
  feature:
    - name: FileAndStorage-Services
    - name: Storage-Services
    ##
    - name: Web-Server
    - name: Web-WebServer
    - name: Web-Common-Http
    - name: Web-Default-Doc
    - name: Web-Dir-Browsing
    - name: Web-Http-Errors
    - name: Web-Static-Content
    - name: Web-Health
    - name: Web-Http-Logging
    - name: Web-Performance
    - name: Web-Stat-Compression
    - name: Web-Security
    - name: Web-Filtering
    - name: Web-Windows-Auth
    - name: Web-App-Dev
    - name: Web-Net-Ext
    - name: Web-Net-Ext45
    - name: Web-Asp-Net
    - name: Web-Asp-Net45
    - name: Web-ISAPI-Ext
    - name: Web-ISAPI-Filter
    - name: Web-Mgmt-Tools
    - name: Web-Mgmt-Console
    - name: Web-Mgmt-Compat
    - name: Web-Metabase
    ##
    - name: NET-Framework-Features
    - name: NET-Framework-Core
    ##
    - name: NET-Framework-45-features
    - name: NET-Framework-45-Core
    - name: NET-Framework-45-ASPNET
    - name: NET-WCF-Services45
    - name: NET-WCF-HTTP-Activation45
    - name: NET-WCF-TCP-PortSharing45
    ##
    - name: FS-SMB1
    ##
    - name: Windows-Defender-Features
    - name: Windows-Defender
    - name: Windows-Defender-GUI
    ##
    - name: PowerShellRoot
    - name: PowerShell
    - name: PowerShell-V2
    - name: PowerShell-ISE
    ##
    - name: WAS
    - name: WAS-Process-Model
    - name: WAS-Config-APIs
    ##
    - name: WoW64-Support
