---
# Authors
# -------
#
# Sami Lanu <sami.lanu@tut.fi>
#
# Copyright
# ---------
#
# Copyright 2018 Tampere University of Technology
- name: install windows Features
  win_feature:
    name: UpdateServices
    source: z:\sources\sxs
    state: Present
